### ISSUE TITLE
Testing best practices

### ISSUE THREAD

**Issue by andreialecu** [stoica94/react-native-modern-template#2]
Just stumbled upon this. Looks good. Might use it to jumpstart future projects!

One minor issue though. In the test example you are using `accessibilityLabel`, which is supposed to be actual text for screen readers. I suggest changing it into `testID` instead, just so new users get used to better practices.

See https://www.native-testing-library.com/docs/example

**Comment by ovistoica** [comment]
Hello. First of all thank you for the interest in the project. I appreciate you took the time to explore the project. Also please tell me if there are any other features you would want added to the project. 

Secondly, it is actually better to test with `accessibilityLabel` which is closer to the real user experience. `testID` is only accessible to dev's. 

From the docs: 

> We also give you the ability to search for elements by testID, but you should consider it a last resort because users can't see a testID and it can introduce unpredictable behavior in your tests.

Also see `How should you query`: https://www.native-testing-library.com/docs/guide-queries

**Comment by andreialecu** [comment]
I see, I guess this issue should be brought upon the `native-testing-library.com/docs` repo instead then. :)

Recommending `getByLabelText` seems wrong to me for a few reasons:

1) It strongly couples the tests to the "copy-writing". Changing the label at some point will require changing the tests as well.
2) It encourages developers to type in non descriptive labels such as `welcome-banner` instead of the full actual text. A screen reader would read "welcome-header" instead of "Welcome to React Native!": https://github.com/stoica94/react-native-modern-template/blob/master/src/components/greetings-banner.tsx#L5-L7 This is likely to create even worse problems that not using `accessibilityLabel` in the first place.
3) More importantly, a lot of apps need to be localized. So once you need to support additional languages, this completely breaks down.

Not sure why they don't recommend using `testID` which is pretty standard.

**Comment by ovistoica** [comment]
I agree you have a point about localization and how do you handle accessibilty with that in mind. 

I will look into that and come back with an answer. Good first issue 👍
